name: stolpersteine
description: "Stolpersteine - Pietre di inciampo"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  http: ^1.3.0
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.2
  flutter_map_animations: ^0.8.0
  dio: ^5.8.0+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

